In [4]:
for i in range(0,4):
    for j in range(0,4):
        if i+j<=2:
            print(" ",end=" ")
        if i+j>=3:
            print("*",end=" ")
    print( )

      * 
    * * 
  * * * 
* * * * 


In [2]:
ls="virat"
for i in range(ls):
    for j in range(1,i+1):
         print("*",end=" ")
    print( )

TypeError: 'str' object cannot be interpreted as an integer

In [6]:
ls=input("enter the name")
for i in range(len(ls)):
    for j in range(0,i+1):
         print(ls[i],end=" ")
    print( )

enter the namevirat
v 
i i 
r r r 
a a a a 
t t t t t 


In [12]:
r={}
n=int(input("enter the num of students"))
i=1
while i<=n:
    nam=input("enter the name of student")
    mark=input("mark in %")
    r[nam]=mark
    i+=1
    print("name of the student","\t","% of marks")
    for x in r:
        print("\t",x,"\t\t",r[x])



enter the num of students2
enter the name of studentabi
mark in %45
name of the student 	 % of marks
	 abi 		 45
enter the name of studentvijay
mark in %99
name of the student 	 % of marks
	 abi 		 45
	 vijay 		 99


In [17]:
word=input("enter any word:")
d={}
for x in word:
    d[x]=d.get(x,0)+1
for k,v in d.items():
    print(k,"occur",v,"times")
    

enter any word:hello
h occur 1 times
e occur 1 times
l occur 2 times
o occur 1 times


In [20]:
word=input("enter any word:")
d={}
for x in word:
    if x in ['a','e','i','o','u']:
        d[x]=d.get(x,0)+1
for k,v in d.items():
     print(k,"occur",v,"times")

enter any word:welcome
e occur 2 times
o occur 1 times


In [ ]:
square={x:x*x for x in range(1,6)}
print(square)

In [3]:
square={x:x*x for x in range(1,6)}
print(square)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [6]:
n=[1,2,3,4,5,5,5,5]
print(n.count(5))

4


In [7]:
print(n.index(5))

4


In [13]:
Cn=[1,2,3,4,5,6,7]
c=n.extend(1,999)
print(c)

TypeError: extend() takes exactly one argument (2 given)

In [14]:
no=[1,2,3,4,5,6,7]
n.extend(no)
print(n)

[1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7]


### name


In [15]:
n=[1,2,3,4]
m=n.pop()
print(m)


4


In [16]:
n.reverse()


In [17]:
print(n)


[3, 2, 1]


In [18]:
n=["kumaran","sunny","ammini","sainab"]
n.sort()
print(n)

['ammini', 'kumaran', 'sainab', 'sunny']


In [19]:
n.sort(reverse=True)

In [20]:
print(n)


['sunny', 'sainab', 'kumaran', 'ammini']


In [22]:
x=[10,20,30,40]
y=x[:2]
y[1]=777
print(x)
print(y)

[10, 20, 30, 40]
[10, 777]


In [23]:
x=[10,20,30,40]    #copy by reference,,,,,,to avoid this we ude slicing
y=x
y[1]=777
print(x)
print(y)

[10, 777, 30, 40]
[10, 777, 30, 40]


In [24]:
x=[10,20,30,40]
y=x.copy()
y[1]=777
print(x)
print(y)

[10, 20, 30, 40]
[10, 777, 30, 40]


In [26]:
a=[10,20,30]
b=[40,50,60]
c=a+b
print(c)

x=[10,20,30]
y=x*3
print(y)

[10, 20, 30, 40, 50, 60]
[10, 20, 30, 10, 20, 30, 10, 20, 30]


In [28]:
x=["MITE","MANGLORE","NITTE"]
y=["MITE","MANGLORE","NITTE"]
x==y
x!=y
z=["MITE","MANGLORE","NITTE"]
x==z

True

In [29]:
m=[10,20,30,50,[60,70,80]]
m[3]
m[4][1]
m.clear()
n=[1,2,3,4]
print(4 in n)

True


In [30]:
s=[2**x for x in range(1,6)]
print(s)


[2, 4, 8, 16, 32]


In [31]:
def prime(num):
    for x in range(1,20):
        if x=2:
            print(x)
        if x%2!=0

SyntaxError: invalid syntax (<ipython-input-31-0808c32ac919>, line 3)

In [32]:
def time(var):
    return var*2
seq=[1,2,3,4,5]
lst(map(time,seq))

NameError: name 'lst' is not defined

In [34]:
seq=[1,2,3,4,5]           #multiples of 2
lambda var:var*2
list(map(lambda var:var*2,seq))
list(filter(lambda item:item%2==0,seq))

[2, 4]

In [35]:
seq=[1,2,3,4,5]
lambda var:var*2
list(map(lambda var:var*2,seq))
filter(lambda item:item%2==0,seq)

In [1]:

import numpy as np

In [2]:
lst=[1,2,3]
lst
np.array(lst)


array([1, 2, 3])

In [3]:
mat=[[1,2,3],[4,5,6],[7,8,9]]
mat
np.array(mat)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,10,2)


array([0, 2, 4, 6, 8])

In [6]:
mat=[[1,2,3],[4,5,6],[7,8,9]]
mat



[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.ones(3,3)

TypeError: data type not understood

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(2)

array([0.94963292, 0.91103511])

In [19]:
np.random.rand(5,5)

array([[0.63413287, 0.90945689, 0.77235958, 0.06528591, 0.99880522],
       [0.21634148, 0.84724421, 0.71332717, 0.79400444, 0.67308755],
       [0.68041412, 0.77844448, 0.88826975, 0.17546459, 0.88516929],
       [0.05464189, 0.66894722, 0.53108837, 0.94572267, 0.11110891],
       [0.31656104, 0.09520499, 0.6103665 , 0.20870565, 0.40546588]])

In [20]:
np.random.randn(5,5)

array([[-0.63908785,  0.67006906, -0.15996828,  0.09376525,  1.03052786],
       [-1.25084145,  0.60587098,  2.2370816 , -0.64251318, -0.53255696],
       [-0.5697131 ,  1.1125708 , -1.20767779, -0.69087642, -0.62059856],
       [-1.33778089,  1.60086712,  0.03390503, -0.85831342, -0.13679855],
       [-2.22523627,  1.20732075, -0.44049608, -2.74312648,  1.6100138 ]])

In [21]:
np.random.randint(1,100,10)

array([91, 30, 86, 96, 49, 50, 81, 33, 47, 19])

In [22]:
arr.reshape(5,5)

NameError: name 'arr' is not defined

In [23]:
arr=np.arange(25)

In [30]:
runarr=np.random.randint(0,50,10)


In [29]:
runarr.max()

48

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
runarr.max()

42

In [33]:
runarr.argmax()

3

In [34]:
argmin and min

NameError: name 'argmin' is not defined

In [35]:
arr.shape

(25,)

In [36]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [37]:
arr.reshape(1,25).shape

(1, 25)

In [38]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [39]:
arr.reshape(25,1).shape

(25, 1)

In [40]:
arr.dtype


dtype('int32')

In [41]:
arr=np.arange(0,10)
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [42]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [43]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [44]:
arr/arr

C:\Users\Vyshnav\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [45]:
1/arr

C:\Users\Vyshnav\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [46]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [48]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [49]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [50]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [51]:
np.log(arr)

C:\Users\Vyshnav\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [52]:
arr=np.arange(0,11)

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr[8]

8

In [55]:
arr[1:5]

array([1, 2, 3, 4])

In [56]:
arr[0,5]

IndexError: too many indices for array

In [57]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [58]:
C

In [59]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [60]:
arr>4

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [61]:
arr[arr>4]

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [65]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [66]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [67]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [68]:
arr[0:10]=5

In [69]:
arr

array([ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5, 10])

In [70]:
arr=np.arange(10,81,2)

In [71]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80])

In [72]:
arr=np.arange(9)
runarr=np.random.randint(0,8,10)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
arr=np.arange(25)
#runarr=np.random.randint(1,25,25)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [5]:
np.random.randn(25)

array([-0.49895651, -0.80728357, -0.60364236, -0.32100168, -1.34402892,
       -1.37176218,  1.25641469, -2.31449959,  0.00265876,  1.5647936 ,
        0.99999174,  0.86736096,  0.4649635 ,  0.14520219, -0.13171214,
       -0.73513512, -0.25780821, -0.43405774,  0.88938835,  1.23809698,
       -0.11412875, -1.87750996, -1.28187287,  0.24208166, -0.37516842])

In [3]:
import numpy as np
x = np.random.randint(low=0, high=25, size=25)
print(x)


[ 6  0  7  0  5 21 11 10  7 15 15 10  8  0 14 19 15  5  1 22  3  8 15 21
 17]


In [6]:
for i in range(0,4):
    for j in range(0,4):
        if i+j<=2:
            print(" ",end=" ")
        if i+j>=3:
            print("*",end=" ")
    print( )

      * 
    * * 
  * * * 
* * * * 


In [1]:
for i in range(0, 4):
    for j in range(0, i+1):
        print("* ",end="")
    print()

* 
* * 
* * * 
* * * * 


In [6]:

for i in range(5):
    for j in range((5- i)):
        print(end=" ")
    for j in range(i + 1):
        print("*", end=" ")
    print()

     * 
    * * 
   * * * 
  * * * * 
 * * * * * 


In [17]:
for i in range(5):
    print("  "*(5-i)," *  "*(i+1))

            *  
          *   *  
        *   *   *  
      *   *   *   *  
    *   *   *   *   *  
